name: feed

on:
  workflow_dispatch:
  push:
    paths:
      - '**.md'
      - '**.php'
      - '.*rc'
      - '.github/**.yaml'
      - '.github/**.yml'
  pull_request:
    paths:
      - '**.md'
      - '**.php'
      - '.*rc'
      - '.github/**.yaml'
      - '.github/**.yml'

jobs:
  feed:
    name: feed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node version
        uses: actions/setup-node@v4

      - name: Install lint-md
        run: npm install @lint-md/cli -g

      - name: Install zhlint
        run: npm install zhlint -g

      - name: Fix markdown
        run: lint-md 'README.md' --config=.lintmdrc --threads --fix

      - name: Fix zh_CN
        run: zhlint 'README.md' --config=.zhlintrc --fix

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install --no-interaction --prefer-dist --ansi -v

      - name: Run feed
        run: ./favorite-link feed:generate --ansi -v

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_options: '--no-verify'
          commit_message: 'Update feed'
          file_pattern: '**.atom **.rss README.md'
